_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 30
                - 41
                - 50
                - 53
                - 55
            "2":
                - 1
                - 5
                - 30
                - 41
                - 50
                - 53
                - 55
            "3":
                - 2
                - 13
                - 16
                - 23
                - 55
                - 61
            "4": 3.9.21
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 64
dataset:
    value: MNIST
epochs:
    value: 2
hp_batch_size:
    value: 64
hp_learning_rate:
    value: 1.7429005050885534e-05
hp_local_epochs:
    value: 2
learning_rate:
    value: 0
model_architecture:
    value: MNISTClassifier
num_rounds:
    value: 20
optimizer:
    value: ""
